In [1]:
# Obtain the following arrays through fancy indexing when given the following array.
#a.)[(1, 12, 23, 34, 45])
#b.)([[30, 32, 35],
#    [40, 42, 45],
#    [50, 52, 55]])
#c.) ([2, 22, 52])

In [7]:
import numpy as np
a = np.arange(6) + np.arange(0, 51, 10)[:, np.newaxis]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

# Answer

In [6]:
a[(0,1,2,3,4), (1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [10]:
a[3:, (0,2,5)]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [11]:
mask = np.array([1,0,1,0,0,1], dtype=bool)
a[mask, 2]

array([ 2, 22, 52])