# Basic Theory Behind Arrays

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
from numpy import *

In [4]:
# a vector: the argument to the array function is a Python list
v = array ([1,2,3,4])
v

array([1, 2, 3, 4])

In [5]:
# a matrix: the argument to the array function is a nested Python list
M = array([[1, 2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [6]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [11]:
v.shape, M.shape #gives the dimensions of an array

((4,), (2, 2))

In [10]:
v.size, M.size #gives the number of elements in an array

(4, 4)

# How to Generate Arrays

In [12]:
# create an array using a range of numbers
x = arange(0, 10, 1) #arguments:(start:stop:stride)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Linspace Function Arguments